### ISSUE TITLE
AttributeError during IAM users scan

### ISSUE THREAD

**Issue by abi5090** [Netflix/security_monkey#873]
I am getting an AttributeError when executing the scan for IAM users. Haven't seen this issue for other resources. What could be the issue? Something to do with a particular user in the account?

```
$ monkey find_changes -a all -m iamuser
2017-11-15 12:00:03,035 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
INFO:apscheduler.threadpool:Started thread pool with 25 core threads and 30 maximum threads
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 695, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 80, in find_changes
    sm_find_changes(account_names, monitor_names)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 57, in find_changes
    audit_changes(accounts, monitor_names, False, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 103, in audit_changes
    _audit_changes(account, monitor.auditors, send_report, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 135, in _audit_changes
    au.audit_objects()
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 668, in audit_objects
    method(item)
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_user.py", line 166, in check_attached_managed_policies
    self.library_check_attached_managed_policies(iamuser_item, 'user')
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_policy.py", line 211, in library_check_attached_managed_policies
    self.link_to_support_item_issues(iam_item, mp_item.db_item, None, "Found issue(s) in attached Managed Policy")
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 958, in link_to_support_item_issues
    issue.sub_items.append(sub_item)
AttributeError: 'NoneType' object has no attribute 'sub_items'
INFO:root:Shutting down thread pool
```
OS - 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by mikegrima** [comment]
@monkeysecurity Was this recently fixed (auditors)?

**Comment by ngtjah** [comment]
I am experiencing the same error for both `iamrole` and `iamuser`.

**Comment by monkeysecurity** [comment]
Very interesting. Can you do a “git log” and let me know what the most
recent commit was? (Top item)

Have you done a “monkey db upgrade” ?

**Comment by ngtjah** [comment]
I just installed this and I'm trying it out today.

I believe I did run `monkey db migrate`. The UI is working and it was collecting. If I go to Search I can see about 4,000 items in the DB.

```
$ git log
commit 86b5df438dc0fbc3b65ab7730fd19f3c42b6dac3
Author: Patrick <patrick@netflix.com>
Date:   Fri Dec 1 21:16:24 2017 +0000

    Adding new permissions for EC2 Image Attributes.
```

**Comment by ngtjah** [comment]
Failure with DEBUG log level.

IAM Group
```
DEBUG:security_monkey:Adding issue: iamgroup/universal/Development/CloudLoaderGroup-15NUYJFFN95GJ
	Sensitive Permissions -- Service [dynamodb] Category: [DataPlaneWriteAccess] Resources: ["arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-ArchiveReportDynamoDb-1OPKI3RVT6UIM", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-ContentDynamoDb-ICTJZ4RH5GVR", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-ContentFileDynamoDb-YD43VU1LYIHS", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-ContentFileUploadingDynamoDb-1SR6XK6IGQ07Q", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-FileReportDynamoDb-1TK68OZQ2FAPW", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-SessionDynamoDb-7MPSP3EEVKKQ", "arn:aws:dynamodb:us-west-2:111111111111:table/WebResources-mayank-TaskDynamoDb-1QINJ6LE8C40T"]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 695, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 80, in find_changes
    sm_find_changes(account_names, monitor_names)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 57, in find_changes
    audit_changes(accounts, monitor_names, False, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 103, in audit_changes
    _audit_changes(account, monitor.auditors, send_report, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 135, in _audit_changes
    au.audit_objects()
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 668, in audit_objects
    method(item)
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_group.py", line 41, in check_attached_managed_policies
    self.library_check_attached_managed_policies(iamgroup_item, 'group')
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_policy.py", line 211, in library_check_attached_managed_policies
    self.link_to_support_item_issues(iam_item, mp_item.db_item, None, "Found issue(s) in attached Managed Policy")
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 958, in link_to_support_item_issues
    issue.sub_items.append(sub_item)
AttributeError: 'NoneType' object has no attribute 'sub_items'
INFO:root:Shutting down thread pool
```

IAM User
```
2017-12-03 02:33:39,388 DEBUG: Adding issue: iamuser/universal/Development/softphoneLogger
	Informational -- Active Accesskey [AKIAILAFMXXXXXXX] [in /usr/local/src/security_monkey/security_monkey/auditor.py:631]
DEBUG:security_monkey:Adding issue: iamuser/universal/Development/softphoneLogger
	Informational -- Active Accesskey [AKIAILAFMXXXXXXX]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 695, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/manage.py", line 80, in find_changes
    sm_find_changes(account_names, monitor_names)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 57, in find_changes
    audit_changes(accounts, monitor_names, False, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 103, in audit_changes
    _audit_changes(account, monitor.auditors, send_report, debug)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 135, in _audit_changes
    au.audit_objects()
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 668, in audit_objects
    method(item)
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_user.py", line 166, in check_attached_managed_policies
    self.library_check_attached_managed_policies(iamuser_item, 'user')
  File "/usr/local/src/security_monkey/security_monkey/auditors/iam/iam_policy.py", line 211, in library_check_attached_managed_policies
    self.link_to_support_item_issues(iam_item, mp_item.db_item, None, "Found issue(s) in attached Managed Policy")
  File "/usr/local/src/security_monkey/security_monkey/auditor.py", line 958, in link_to_support_item_issues
    issue.sub_items.append(sub_item)
AttributeError: 'NoneType' object has no attribute 'sub_items'
INFO:root:Shutting down thread pool
```

**Comment by monkeysecurity** [comment]
I have reproduced this bug in my dev environment.  Upping priority to blocker.

**Comment by monkeysecurity** [comment]
I’ve created a PR #891 to address this issue.

Root cause:  If an IAM User/Group/Role had a managed policy attached and that managed policy had zero issues, it would cause this exception.  (Not good.)

**Comment by monkeysecurity** [comment]
I’ve merged the PR.  I believe this issue is solved.  Please re-open if needed.

**Comment by D4rk4** [comment]
@monkeysecurity problem not solved. I just upgrade secmonkey from git (follow by your instruction), and run find_changes.
Result:
```
2017-12-20 09:09:03,324 INFO: Started thread pool with 25 core threads and 30 maximum threads [in /usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/APScheduler-2.1.2-py2.7.egg/apscheduler/threadpool.py:52]
INFO:apscheduler.threadpool:Started thread pool with 25 core threads and 30 maximum threads
INFO:botocore.credentials:Credentials found in config file: ~/.aws/config
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-northeast-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-northeast-2.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-south-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-southeast-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-southeast-2.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ca-central-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.eu-central-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.eu-west-2.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.eu-west-3.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.sa-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-east-2.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/bin/monkey", line 11, in <module>
    load_entry_point('security-monkey==0.9.3', 'console_scripts', 'monkey')()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/manage.py", line 695, in main
    manager.run()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/manage.py", line 80, in find_changes
    sm_find_changes(account_names, monitor_names)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/scheduler.py", line 54, in find_changes
    cw.save()
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/watcher.py", line 486, in save
    item.save(self.datastore)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/watcher.py", line 635, in save
    ephemeral=ephemeral)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/datastore.py", line 635, in store
    item.latest_revision_complete_hash = self.hash_config(config)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/datastore.py", line 550, in hash_config
    item = sub_dict(config)
  File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/common/utils.py", line 54, in sub_dict
    for k in d:
TypeError: 'NoneType' object is not iterable
INFO:root:Shutting down thread pool
```

**Comment by rayj-pgi** [comment]
I'm seeing it as well.

```
2017-12-20 00:10:29,160 ERROR: Job "run_change_reporter (trigger: interval[1:00:00], next run at: 2017-12-20 01:00:18.991745)" raised an exception [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-2.1.2-py2.7.egg/apscheduler/scheduler.py:520]
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/APScheduler-2.1.2-py2.7.egg/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 32, in run_change_reporter
    reporter.run(account, interval)
  File "/usr/local/src/security_monkey/security_monkey/reporter.py", line 60, in run
    monitor.watcher.save()
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 486, in save
    item.save(self.datastore)
  File "/usr/local/src/security_monkey/security_monkey/watcher.py", line 635, in save
    ephemeral=ephemeral)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 635, in store
    item.latest_revision_complete_hash = self.hash_config(config)
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 550, in hash_config
    item = sub_dict(config)
  File "/usr/local/src/security_monkey/security_monkey/common/utils.py", line 54, in sub_dict
    for k in d:
TypeError: 'NoneType' object is not iterable
```

**Comment by D4rk4** [comment]
@monkeysecurity please reopen

**Comment by mstair** [comment]
Can you enable DEGUG for the console and re-run `monkey find_changes`? Looks like @D4rk4's might be somewhere in ec2:

In env-config/config.py:
```
    'loggers': {
        'security_monkey': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG'
        },
        'apscheduler': {
            'handlers': ['file', 'console'],
            'level': 'INFO'
        }
    }
```

**Comment by D4rk4** [comment]
@mstair alredi in config, but where i can find extra info?
I update to last GIT HEAD, but problem don't disappear
